export interface EmojiItem {
  emoji: string;
  name: string;
  keywords: string[];
}

type RawEmoji = [string, string, string[]];

const rawSmileysPeople: RawEmoji[] = [
  ["😀", "Grinning face", ["happy", "smile", "joy", "cheerful"]],
  ["😃", "Grinning face big eyes", ["happy", "smile", "joy", "excited"]],
  ["😄", "Grinning squinting face", ["happy", "smile", "joy", "laugh"]],
  ["😁", "beaming face smiling eyes", ["happy", "smile", "grin", "proud"]],
  ["😆", "Grinning squinting face", ["happy", "smile", "laugh", "giggle"]],
  ["😅", "Grinning sweat face", ["happy", "smile", "relief", "sweat", "nervous"]],
  ["😂", "Face with tears of joy", ["laugh", "crying", "lol", "haha", "funny"]],
  ["🤣", "Rolling on floor laughing", ["laugh", "lol", "haha", "funny", "rofl"]],
  ["😊", "Smiling face smiling eyes", ["happy", "smile", "warm", "blush", "kind"]],
  ["😇", "Smiling face halo", ["angel", "holy", "innocent", "good", "perfect"]],
  ["🙂", "Slightly smiling face", ["happy", "smile", "meh", "okay"]],
  ["🙃", "Upside-down face", ["sarcasm", "irony", "silly", "flipped"]],
  ["😉", "Winking face", ["wink", "flirt", "joke", "mischievous"]],
  ["😌", "Relieved face", ["calm", "peaceful", "relaxed", "phew", "satisfied"]],
  ["😍", "Heart eyes", ["love", "crush", "gorgeous", "adore", "heart"]],
  ["🥰", "Smiling face hearts", ["love", "affection", "warmth", "cute", "adorable"]],
  ["😘", "Blow a kiss", ["love", "kiss", "muah", "affection", "goodnight"]],
  ["😗", "Kissing face", ["kiss", "whistle", "duck"]],
  ["😙", "Kissing smiling eyes", ["kiss", "happy", "affection"]],
  ["😚", "Kissing closed eyes", ["kiss", "blush", "intimate", "love"]],
  ["😋", "Savoring food face", ["yummy", "delicious", "hungry", "tongue", "taste"]],
  ["😛", "Face tongue out", ["silly", "joke", "playful", "cheeky"]],
  ["😜", "Winking tongue out", ["wink", "silly", "joke", "prank"]],
  ["🤪", "Zany crazy face", ["wild", "goofy", "silly", "insane", "eccentric"]],
  ["😝", "Squinting tongue out", ["silly", "disgust", "taste", "playful"]],
  ["🤑", "Money mouth face", ["cash", "rich", "dollar", "wealth", "greedy"]],
  ["🤗", "Hugging face", ["hands", "hug", "greet", "warmth", "welcome"]],
  ["🫣", "Peeking eye face", ["fear", "scared", "hide", "seek", "curious"]],
  ["🤭", "Hand over mouth giggle", ["secret", "gasp", "accident", "oops"]],
  ["🫢", "Open mouth hand", ["shock", "disbelief", "surprise", "gasp"]],
  ["🫡", "Saluting face", ["respect", "yes", "sir", "honor"]],
  ["🤔", "Thinking face", ["hmm", "wonder", "ponder", "curious", "reflect"]],
  ["🤫", "Shushing face", ["quiet", "shh", "silence", "secret"]],
  ["🫠", "Melting face", ["hot", "dissolve", "embarrassed", "overwhelmed"]],
  ["🤫", "Whispering quiet", ["shh", "silence", "secret"]],
  ["🫢", "Covering mouth shock", ["surprise", "shock", "gasp"]],
  ["🫨", "Shaking face", ["earthquake", "dizzy", "vibrate", "tremble", "scared"]],
  ["🤐", "Zipper mouth face", ["secret", "silent", "quiet", "shutup", "mouth"]],
  ["🤨", "Raised eyebrow face", ["skeptical", "hmm", "distrust", "confused"]],
  ["😐", "Neutral face", ["meh", "okay", "flat", "unimpressed"]],
  ["😑", "Expressionless face", ["bored", "annoyed", "flat", "seriously"]],
  ["😬", "Grimacing face", ["awkward", "oops", "nervous", "cringe"]],
  ["🫨", "Shaking blur face", ["shock", "dizzy", "vibe"]],
  ["🤥", "Lying long nose", ["pinocchio", "fake", "liar", "deceit"]],
  ["😌", "Relieved calm", ["peace", "saved", "sleeping"]],
  ["😴", "Sleeping face zzz", ["sleep", "tired", "bed", "rest", "night"]],
  ["😪", "Sleepy face tear", ["tired", "exhausted", "sleep", "sad"]],
  ["🤤", "Drooling face yummy", ["yummy", "delicious", "hungry", "mouth"]],
  ["🤢", "Nauseous green face", ["sick", "disgust", "gross", "vomit"]],
  ["🤮", "Vomiting face", ["puke", "sick", "gross", "unhealthy"]],
  ["🤧", "Sneezing face", ["cold", "sick", "allergy", "tissue", "flu"]],
  ["🥵", "Hot red face", ["warm", "heat", "summer", "sweat", "spicy"]],
  ["🥶", "Cold blue face", ["ice", "winter", "freeze", "chilly"]],
  ["🥴", "Woozy dizzy face", ["drunk", "tipsy", "high", "confused", "blurred"]],
  ["😵", "Dizzy dead eyes", ["shock", "dead", "knocked", "crossed"]],
  ["😵‍💫", "Spiral eyes dizzy", ["hypnotized", "confused", "spins"]],
  ["🤯", "Exploding head blown", ["mindblown", "shock", "amazing", "eureka"]],
  ["🤠", "Cowboy hat face", ["western", "yeehaw", "texas", "country"]],
  ["🥳", "Celebrating party face", ["birthday", "cheers", "confetti"]],
  ["🥸", "Disguised face mask", ["spy", "detective", "hidden", "glasses"]],
  ["😎", "Cool sunglasses", ["sun", "swag", "glasses", "chill"]],
  ["🤓", "Nerd face glasses", ["smart", "geek", "study", "exam", "books"]],
  ["🧐", "Monocle face", ["fancy", "investigate", "smart", "classy"]],
  ["😕", "Confused face", ["hmm", "perplexed", "lost", "doubt"]],
  ["😟", "Worried face", ["scared", "fear", "anxious", "nervous"]],
  ["🙁", "Slightly frowning face", ["sad", "unhappy", "blue"]],
  ["☹️", "Frowning traditional face", ["sad", "crying", "unhappy"]],
  ["😮", "Open mouth surprise", ["shock", "wow", "startled"]],
  ["😯", "Hushed amazed face", ["shock", "silent", "quiet"]],
  ["😲", "Astonished wide eyes", ["shock", "gasp", "amazed", "surprise"]],
  ["😳", "Flushed red cheeks", ["blush", "embarrassed", "shy", "shock"]],
  ["🥺", "Pleading begging face", ["puppy", "please", "sad", "beg", "cute"]],
  ["🥹", "Holding back tears", ["happy-cry", "grateful", "emotional"]],
  ["😦", "Frowning open mouth", ["gasp", "shocked", "fear"]],
  ["😧", "Anguished distress face", ["pain", "hurt", "gasp", "fear"]],
  ["😨", "Fearful face", ["scared", "spooky", "fright", "anxious"]],
  ["😰", "Anxious sweat blue forehead", ["scared", "sweat", "nervous", "stressed"]],
  ["😥", "Sad relieved sweat", ["crying", "relief", "sweat", "hurt"]],
  ["😢", "Crying face tear", ["sad", "blue", "tears", "lonely", "sorrow"]],
  ["😭", "Loudly crying weeping", ["sad", "bawling", "tears", "shattered", "pain"]],
  ["😱", "Screaming in fear", ["scared", "shock", "spooky", "halloween"]],
  ["😖", "Confounded squint face", ["struggle", "pain", "tight", "upset"]],
  ["😣", "Persevering face", ["stiff", "try", "hard", "struggle"]],
  ["😞", "Disappointed sad face", ["blue", "unhappy", "sorry"]],
  ["😓", "Sweat face downcast", ["exhausted", "stressed", "sweat", "sad"]],
  ["😩", "Weary tired face", ["exhausted", "done", "whine", "sad"]],
  ["😫", "Tired face open mouth", ["broken", "exhausted", "done", "loud"]],
  ["🥱", "Yawning face", ["sleep", "bored", "exhausted", "lazy"]],
  ["😤", "Face with steam nose", ["angry", "winning", "pride", "huff", "rage"]],
  ["😡", "Pouting red angry", ["mad", "rage", "hate", "furious"]],
  ["😠", "Angry face", ["mad", "grumble", "annoyed"]],
  ["🤬", "Cursing symbols mouth", ["angry", "rage", "swear", "furious"]],
  ["😈", "Smiling devil horns", ["devil", "mischief", "evil", "purple"]],
  ["👿", "Angry devil horns", ["devil", "rage", "evil", "purple"]],
  ["💀", "Skull bone dead", ["spooky", "goth", "danger", "dead"]],
  ["☠️", "Skull crossbones flag", ["danger", "pirate", "dead", "poison"]],
  ["👹", "Japanese ogre mask", ["scary", "red", "monster", "demon"]],
  ["👺", "Japanese goblin mask", ["scary", "red", "nose", "monster"]],
  ["👻", "Ghost spooky white", ["spirit", "scary", "halloween", "goth"]],
  ["👽", "Alien outer space", ["space", "cosmic", "sci-fi", "ufo"]],
  ["👾", "Space invader pixel", ["gaming", "game", "retro", "arcade"]],
  ["🤖", "Robot face steel", ["tech", "coding", "ai", "machine"]],
  ["💩", "Pile of poop smiles", ["funny", "brown", "joker", "dung"]],
  ["😺", "Smiling cat face", ["pet", "meow", "kitten"]],
  ["😸", "Grinning cat face", ["pet", "meow", "kitten", "joy"]],
  ["😹", "Cat tears of joy", ["laugh", "meow", "lol", "funny"]],
  ["😻", "Cat heart eyes", ["love", "meow", "adorable", "adore"]],
  ["😼", "Smirking cat face", ["wry", "meow", "smart", "sass"]],
  ["😽", "Kissing cat face", ["love", "kiss", "meow"]],
  ["🙀", "Weary cat shocked", ["scared", "meow", "shock"]],
  ["😿", "Crying cat face", ["sad", "tears", "meow"]],
  ["😾", "Pouting cat face", ["angry", "mad", "meow"]],
  ["👋", "Waving hand sign", ["hello", "bye", "greet", "friendly"]],
  ["🤚", "Raised back of hand", ["hand", "back", "salute"]],
  ["🖐️", "Splayed fingers hand", ["hand", "five", "stop"]],
  ["✋", "Raised flat hand", ["stop", "wave", "salute", "five"]],
  ["🖖", "Vulcan salute", ["spock", "star-trek", "sci-fi", "peace"]],
  ["👌", "Ok hand sign", ["okay", "perfect", "good", "agree"]],
  ["🤌", "Pinched fingers", ["italian", "question", "what", "chef"]],
  ["🤏", "Pinching hand small", ["tiny", "little", "fraction"]],
  ["✌️", "Victory peace sign", ["two", "peace", "v-sign", "happy"]],
  ["🤞", "Crossed fingers luck", ["hope", "promise", "gamble"]],
  ["🫰", "Hand crossing fingers", ["love", "kpop", "heart", "snap"]],
  ["🤟", "Love you gesturing", ["cool", "signing", "rockstar"]],
  ["🤘", "Sign of horns rock", ["metal", "guitar", "concert", "cool"]],
  ["🤙", "Call me hand gesture", ["phone", "hangloose", "surf"]],
  ["👈", "Left pointing index", ["point", "finger", "direction"]],
  ["👉", "Right pointing index", ["point", "finger", "direction"]],
  ["👆", "Up pointing index", ["point", "finger", "direction", "sky"]],
  ["🖕", "Middle finger sign", ["rude", "swear", "angry"]],
  ["👇", "Down pointing index", ["point", "finger", "below"]],
  ["☝️", "Index pointing up", ["point", "count", "one"]],
  ["👍", "Thumbs up sign", ["yes", "good", "like", "agree", "perfect"]],
  ["👎", "Thumbs down sign", ["no", "bad", "dislike", "reject"]],
  ["✊", "Raised fist power", ["solidarity", "punch", "strength"]],
  ["👊", "Oncoming fist punch", ["hit", "strike", "fistbump"]],
  ["🤛", "Leftward facing fist", ["fistbump", "punch"]],
  ["🤜", "Rightward facing fist", ["fistbump", "punch"]],
  ["👏", "Clapping hands applause", ["bravo", "victory", "cheerful"]],
  ["🙌", "Raising hands cheer", ["celebrate", "wow", "hurray"]],
  ["👐", "Open hands warm", ["hug", "open", "sharing"]],
  ["🤲", "Palms up together", ["prayer", "book", "holding"]],
  ["🤝", "Handshake agreement", ["deal", "business", "friends", "trust"]],
  ["🙏", "Folded hands prayer", ["please", "thankyou", "hope", "meditate"]],
  ["✍️", "Writing hand pen", ["coding", "sign", "homework"]],
  ["💅", "Nail polish manicured", ["slay", "fashion", "glam", "aesthetic"]],
  ["🤳", "Taking a selfie", ["phone", "camera", "picture"]],
  ["💪", "Flexed biceps muscle", ["power", "gym", "strength", "workout"]],
  ["🦾", "Mechanical robotic arm", ["cyborg", "prosthetic", "tech"]],
  ["🦿", "Mechanical robotic leg", ["cyborg", "prosthetic", "tech"]],
  ["🦵", "Human bare leg", ["kick", "fitness", "limb"]],
  ["🦶", "Bare human foot", ["step", "barefoot", "walk"]],
  ["👂", "Human hearing ear", ["sound", "listen", "gossip"]],
  ["🦻", "Ear with hearing aid", ["medical", "accessibility"]],
  ["👃", "Human nose smelling", ["smell", "scent", "sniff"]],
  ["🧠", "Human thinking brain", ["smart", "nerd", "mind", "genius", "intellect"]],
  ["🫀", "Anatomical red heart", ["heart", "cardio", "doctor", "organ"]],
  ["🫁", "Anatomical double lungs", ["breath", "breathing", "respiratory"]],
  ["🦷", "White tooth enamel", ["dentist", "smile", "hygiene"]],
  ["BONE", "White dog bone", ["skeleton", "pets", "calcium"]],
  ["👀", "Double looking eyes", ["gaze", "curious", "watch", "secret"]],
  ["👁️", "Single human eye", ["vision", "gaze", "prism"]],
  ["👅", "Outstretched pink tongue", ["taste", "silly"]],
  ["👄", "Red glossy lips", ["kiss", "beauty", "makeup", "mouth"]]
];

const rawAnimalsNature: RawEmoji[] = [
  ["🐶", "Cute puppy dog", ["pets", "bark", "friend", "canine"]],
  ["🐱", "Cute kitty cat", ["pets", "meow", "aesthetic", "kitten"]],
  ["🐭", "Grey field mouse", ["rat", "cheese", " rodent"]],
  ["🐹", "Chubby hamster", ["pet", "wheel", "cute"]],
  ["🐰", "White bunny rabbit", ["bunny", "spring", "easter", "hops"]],
  ["🦊", "Red sly fox", ["forest", "animal", "nature", "wild"]],
  ["🐻", "Brown grizzly bear", ["forest", "teddy", "wild"]],
  ["🐼", "Chubby panda bear", ["bamboo", "china", "cute", "black-white"]],
  ["🐻‍❄️", "White polar bear", ["arctic", "ice", "snow", "north"]],
  ["🐨", "Cute koala bear", ["australia", "eucalyptus", "lazy"]],
  ["🐯", "Orange tiger stripes", ["safari", "wild", "cat", "stripes"]],
  ["🦁", "Proud lion king", ["safari", "wild", "cat", "mane"]],
  ["🐮", "Spotted cow face", ["farm", "dairy", "milk"]],
  ["🐷", "Pink pig snout", ["farm", "bacon", "oink"]],
  ["🐽", "Pig nose snout", ["farm", "pig"]],
  ["🐸", "Green forest frog", ["amphibian", "pond", "ribbit", "cute"]],
  ["🐵", "Monkey face brown", ["jungle", "wild", "banana", "chimpanzee"]],
  ["🙈", "See-no-evil monkey", ["hide", "secret", "gasp", "blind"]],
  ["🙉", "Hear-no-evil monkey", ["deaf", "quiet", "shh"]],
  ["🙊", "Speak-no-evil monkey", ["shutup", "silent", "secret"]],
  ["🐒", "Capuchin climbing monkey", ["jungle", "climb", "tree"]],
  ["🐔", "Rooster chicken bird", ["farm", "egg", "cluck", "morning"]],
  ["🐧", "Chubby arctic penguin", ["cold", "antarctic", "ice", "swim"]],
  ["🐦", "Simple blue fly bird", ["flying", "sky", "tweet"]],
  ["🐤", "Front-facing baby chick", ["bird", "yellow", "egg"]],
  ["🐣", "Hatching baby chick", ["bird", "egg", "born", "spring"]],
  ["🐥", "Standing baby chick", ["bird", "yellow", "spring", "cute"]],
  ["🦆", "Green mallard duck", ["pond", "water", "quack"]],
  ["🦅", "Golden flying eagle", ["usa", "predator", "freedom"]],
  ["🦉", "Wise night owl", ["birds", "smart", "night", "knowledge"]],
  ["🦇", "Dark gothic bat", ["dracula", "goth", "night", "spooky"]],
  ["🐺", "Grey forest wolf", ["canine", "howl", "pack", "moon"]],
  ["🐗", "Wild tusk boar", ["forest", "pig", "savage"]],
  ["🐴", "Brown horse head", ["farm", "run", "ride", "stable"]],
  ["🦄", "Magic pastel unicorn", ["fantasy", "rainbow", "sparkles", "magical"]],
  ["🐝", "Golden stripes honeybee", ["insect", "buzz", "flower", "honey"]],
  ["🪱", "Pink garden worm", ["soil", "earth", "dirt"]],
  ["🐛", "Green fuzzy caterpillar", ["insect", "leaf", "cocoon"]],
  ["🦋", "Blue monarch butterfly", ["wings", "gothic", "aesthetic", "nature"]],
  ["🐌", "Slow garden snail", ["shell", "slime", "slow"]],
  ["🐞", "Red ladybug beetle", ["insect", "dots", "luck", "garden"]],
  ["Ant", "Tiny black ant", ["insect", "colony", "picnic"]],
  ["🪲", "Iridescent green beetle", ["bug", "insect", "shell"]],
  ["🪳", "Brown crawling cockroach", ["bug", "insect", "survivor"]],
  ["🕷️", "Dark spooky spider", ["goth", "halloween", "crawl", "insect"]],
  ["🕸️", "Spooky spider web", ["goth", "halloween", "attic", "gothic"]],
  ["🦂", "Stinging desert scorpion", ["zodiac", "poison", "claw", "desert"]],
  ["Mosquito", "Biting blood mosquito", ["bug", "insect", "summer", "sting"]],
  ["🦎", "Green tail lizard", ["reptile", "gecko", "safari"]],
  ["🐍", "Green venomous snake", ["reptile", "hiss", "poison", "slytherin"]],
  ["🐢", "Green sea turtle", ["shell", "slow", "ocean", "swim"]],
  ["🦖", "Roaring Tyrannosaurus Rex", ["dino", "jurassic", "rawr", "monster"]],
  ["🦕", "Long neck Brontosaurus", ["dino", "jurassic", "nature"]],
  ["🐙", "Purple deep octopus", ["sea", "ocean", "tentacles", "kraken"]],
  ["🦑", "Giant deepsea squid", ["sea", "ocean", "calamari"]],
  ["🦐", "Small pink shrimp", ["seafood", "sea", "ocean"]],
  ["🦞", "Red tusk lobster", ["seafood", "ocean", "claws"]],
  ["🦀", "Red beach crab", ["zodiac", "ocean", "claws", "sand"]],
  ["🐡", "Blowfish puffer fish", ["sea", "ocean", "spike", "poison"]],
  ["🐠", "Tropical orange fish", ["sea", "ocean", "aquarium", "reef"]],
  ["🐟", "Standard blue fish", ["sea", "ocean", "water", "fishing"]],
  ["🐬", "Leaping beach dolphin", ["swim", "sea", "ocean", "water", "smart"]],
  ["🐳", "Spouting ocean whale", ["sea", "water", "marine", "mammal"]],
  ["🐋", "Humpback deep whale", ["sea", "ocean", "marine"]],
  ["Shark", "Great white shark", ["ocean", "teeth", "predator", "jaws"]],
  ["🐊", "Scary swamp crocodile", ["alligator", "swamp", "teeth"]],
  ["Leopard", "Spotted wild leopard", ["spots", "cat", "safari", "fast"]],
  ["Tiger", "Roaring wild tiger", ["cat", "stripes", "jungle"]],
  ["🐃", "Water buffalo tusk", ["farm", "asia"]],
  ["🐂", "Ox farm animal", ["zodiac", "horn", "bull"]],
  ["Cow", "Domestic milk cow", ["farm", "grass", "pasture"]],
  ["Deer", "Forest buck deer", ["woods", "antlers", "bambi", "nature"]],
  ["Camel", "Desert single camel", ["sahara", "hump", "dunes"]],
  ["🐫", "Bactrian double camel", ["desert", "hump", "asia"]],
  ["🦙", "Fluffy white llama", ["alpaca", "andes", "cute", "wool"]],
  ["🦒", "Tall safari giraffe", ["neck", "spots", "savanna"]],
  ["Elephant", "Trunk grey elephant", ["safari", "india", "savanna"]],
  ["🦣", "Woolly tusk mammoth", ["extinct", "ice-age", "paleo"]],
  ["Rhinoceros", "Horn wild rhino", ["savanna", "safari", "armor"]],
  ["🦛", "Purple heavy hippo", ["swamp", "safari", "savanna"]],
  ["Mouse", "Tiny white mouse", ["pet", "lab", "cheese"]],
  ["Rabbit", "Fluffy grey rabbit", ["bunny", "cute", "hops"]],
  ["Chipmunk", "Nut eating chipmunk", ["squirrel", "forest", "acorn"]],
  ["🦫", "River wood beaver", ["dam", "forest", "nature"]],
  ["🦔", "Spiky little hedgehog", ["spike", "cute", "sonic", "pet"]],
  ["Otter", "Floating river otter", ["sea", "swim", "cute", "holdhands"]],
  ["Sloth", "Slow hanging sloth", ["lazy", "tree", "jungle", "slow"]],
  ["🦡", "Stripped forest badger", ["woods", "burrow", "hufflepuff"]],
  ["🌲", "Evergreen pine tree", ["forest", "woods", "mountain", "pine"]],
  ["Trees", "Deciduous forest canopy", ["woods", "park", "nature", "green"]],
  ["🌴", "Tropical palm tree", ["beach", "island", "coconut", "vacation"]],
  ["Cactus", "Desert sandy cactus", ["spike", "dry", "warm", "plant"]],
  ["🌾", "Rice sheaf ear of corn", ["wheat", "agriculture", "autumn"]],
  ["Herb", "Green healing herb", ["leaf", "garden", "organic", "tea"]],
  ["🍀", "Four leaf clover look", ["st-patricks", "green", "lucky", "luck"]],
  ["Maple", "Red autumn maple leaf", ["fall", "canada", "season", "brown"]],
  ["🍂", "Falling winds maple leaf", ["autumn", "season", "leaves"]],
  ["🍃", "Fluttering green leaf", ["wind", "breeze", "spring", "nature"]],
  ["Mushroom", "Red gills mushroom Toadstool", ["fungus", "fairycore", "woods", "magic"]],
  ["Shell", "Spiraled ocean seashell", ["beach", "sea", "shore", "mermaid"]],
  ["Rock", "Solid grey rock", ["stone", "boulder", "nature"]],
  ["Wood", "Logs cut firewood", ["timber", "fireplace", "cabin"]],
  ["Sunflower", "Bright yellow sun flower", ["summer", "yellow", "seeds"]],
  ["🌸", "Cherry blossom petals", ["flower", "spring", "cherry", "pink"]],
  ["🌹", "Romantic red love rose", ["valentines", "floral", "beauty"]],
  ["Tulip", "Pink cup tulip bloom", ["flower", "spring", "garden"]],
  ["🌼", "Yellow blossom flower", ["spring", "daisy", "blooms"]],
  ["💮", "White cherry flower stamp", ["japan", "good-work", "badge"]],
  ["🌺", "Summer exotic hibiscus", ["aloha", "hawaii", "tropical", "beach"]],
  ["Christmas", "Decorated holiday pine tree", ["xmas", "santa", "winter"]],
  ["Onion", "Golden pungent onion", ["vegetable", "tear", "cooking"]],
  ["Garlic", "White bulb garlic head", ["cook", "spice", "vampire"]]
];

const rawFoodDrink: RawEmoji[] = [
  ["🍕", "Cheesy pizza slice", ["cheese", "pepperoni", "dinner", "fastfood"]],
  ["🍔", "Double cheeseburger", ["patty", "fastfood", "bun", "restaurant"]],
  ["🍟", "Golden french fries", ["potato", "salt", "snack", "mcdonalds"]],
  ["🌮", "Mexican spicy taco", ["shell", "meat", "tuesday"]],
  ["🍣", "Fresh sushi roll", ["japan", "fish", "rice", "seafood"]],
  ["🍜", "Steaming ramen bowl", ["noodles", "japan", "soup"]],
  ["🍛", "Curry rice platter", ["curry", "dinner", "spicy"]],
  ["🍦", "Soft serve ice cream", ["summer", "dessert", "sweet", "cold"]],
  ["🍩", "Glazed pink donut", ["doughnut", "sweet", "bakery"]],
  ["🍪", "Chocolate chip cookie", ["baking", "sweet", "milk"]],
  ["🧁", "Tasty baked cupcake", ["sprinkles", "frosting", "dessert"]],
  ["🍉", "Summer watermelon slice", ["fruit", "green", "pink", "refreshing"]],
  ["🥑", "Green avocado half", ["toast", "healthy", "vegan"]],
  ["☕", "Hot brewed coffee", ["morning", "mug", "cafe", "tea"]],
  ["🍵", "Japanese green tea matcha", ["cup", "healthy", "warm"]],
  ["🥤", "Sweet boba cup", ["bubble-tea", "shake", "straw"]],
  ["🍺", "Foamy beer mug", ["bar", "brew", "cheers", "party"]],
  ["🍷", "Red wine glass", ["fancy", "grape", "dinner"]],
  ["🍏", "Crisp green apple", ["fruit", "diet", "healthy"]],
  ["🍎", "Red organic apple", ["fruit", "teacher", "sweet"]],
  ["Pear", "Sweet yellow pear", ["fruit", "orchard"]],
  ["Orange", "Citrus orange slice", ["fruit", "juice", "vitamin"]],
  ["Lemon", "Yellow sour lemon", ["citrus", "sour", "acid", "tea"]],
  ["Banana", "Yellow sweet banana", ["fruit", "monkey", "potassium"]],
  ["Grapes", "Grape bunches purple", ["fruit", "wine", "vineyard"]],
  ["🍓", "Juicy strawberry", ["fruit", "red", "sweet", "berry"]],
  ["Blueberry", "Wild fresh blueberries", ["fruit", "muffin", "blue"]],
  ["Melon", "Green sweet melon", ["cantaloupe", "honeydew", "fruit"]],
  ["🍒", "Double cherry bunch", ["sweet", "aesthetic", "fruit"]],
  ["Peach", "Fuzzy pink peach", ["fruit", "butt", "sweet"]],
  ["Mango", "Sweet gold mango", ["tropical", "juice", "sweet"]],
  ["Pineapple", "Tropical sweet pineapple", ["exotic", "aloha", "pizza"]],
  ["Coconut", "Brown cracked coconut", ["tropical", "beach", "exotic"]],
  ["Kiwi", "Fuzzy brown kiwi fruit", ["fruit", "green"]],
  ["Tomato", "Red juicy tomato", ["vegetable", "salad", "sauce"]],
  ["Aubergine", "Purple long eggplant", ["vegetable", "nsfw", "emoji"]],
  ["Broccoli", "Green broccoli tree", ["vegetable", "healthy", "green"]],
  ["Lettuce", "Green crisp cabbage head", ["vegetable", "salad", "diet"]],
  ["Cucumber", "Green fresh cucumber", ["vegetable", "pickle", "spa"]],
  ["Chili", "Spicy hot red chili", ["spicy", "pepper", "mexican", "warm"]],
  ["Corn", "Sweet maize ear of corn", ["yield", "farm", "popcorn"]],
  ["Carrot", "Orange sweet carrot", ["vegetable", "rabbit", "vision"]],
  ["Potato", "Brown baked potato", ["fries", "tater", "chips"]],
  ["Bread", "Baked loaf of bread", ["bakery", "slice", "carb"]],
  ["Croissant", "Buttery french croissant", ["bakery", "pastry", "breakfast"]],
  ["Baguette", "Crisp french bread stick", ["paris", "bakery", "carb"]],
  ["Flatbread", "Pita warm flatbread", ["roti", "wrap", "naan"]],
  ["Pretzel", "Salted twisted pretzel", ["snack", "german", "bakery"]],
  ["Bagel", "Baked round bagel", ["breakfast", "creamcheese", "carb"]],
  ["Pancakes", "Stack of hot pancakes", ["syrup", "breakfast", "butter"]],
  ["Waffle", "Belgian hot waffle grid", ["breakfast", "dessert", "syrup"]],
  ["Cheese", "Swiss yellow cheese block", ["mouse", "cheddar", "pack"]],
  ["Meat", "T-bone raw steak cuts", ["beef", "grill", "butcher", "dinner"]],
  ["Poultry", "Fried chicken drumstick", ["poultry", "meat", "finger-licking"]],
  ["Bacon", "Smoked crispy bacon strips", ["breakfast", "pork", "sizzle"]],
  ["Hotdog", "Grilled sausage in bun", ["fastfood", "mustard", "streetfood"]],
  ["Sandwich", "Deli double decker sandwich", ["bread", "lunch", "picnic"]],
  ["Burrito", "Wrapped Mexican beef burrito", ["beans", "mexican", "wrap"]],
  ["Popcorn", "Movie theater popcorn bucket", ["theater", "snack", "butter"]],
  ["Bento", "Japanese partition bento box", ["lunch", "sushi", "japanese"]],
  ["Ricecracker", "Japanese senbei rice cracker", ["snack", "crunchy"]],
  ["Riceball", "Japanese seaweed onigiri", ["japan", "anime", "snack"]],
  ["Rice", "Steaming bowl white rice", ["sushi", "grain", "asia"]],
  ["Yam", "Roasted sweet potato yam", ["snack", "autumn"]],
  ["Oden", "Japanese skewer oden skewers", ["seafood", "broth", "winter"]],
  ["Fishcake", "Japanese narutomaki swirl", ["ramen", "soup", "pink"]],
  ["Mooncake", "Golden mid-autumn mooncake", ["festival", "chinese", "bakery"]],
  ["Dango", "Sweet colors dango skewers", ["japan", "sweet", "dessert"]],
  ["Dumpling", "Gyoza steamed dumpling", ["chinese", "potsticker", "snack"]],
  ["Oyster", "Shell fresh ocean oyster", ["seafood", "pearl", "aphrodisiac"]],
  ["Shavedice", "Rainbow shaved ice cone", ["summer", "cold", "syrup"]],
  ["Sundae", "Glass bowl ice cream sundae", ["cherry", "dessert", "chocolate"]],
  ["Cake", "Frosted birthday cake candle", ["party", "celebration", "sweet"]],
  ["Chocolate", "Brown wrapped chocolate bar", ["sweet", "cocoa", "candy"]],
  ["Candy", "Wrapped sweet fruit candy", ["sweet", "halloween", "treating"]],
  ["Lollipop", "Swirl rainbow lollipop", ["sweet", "sugar", "candy"]],
  ["Custard", "Flan caramel pudding custard", ["dessert", "french"]],
  ["Honey", "Golden pot honey bees", ["sweet", " Winnie", "breakfast"]],
  ["Babybottle", "Milky clear baby bottle", ["baby", "drink", "kid"]],
  ["Milk", "Glass of cold milk", ["dairy", "cookie", "calcium"]],
  ["Teapot", "Ceramic brewing tea pot", ["tea", "cozy", "english", "herbal"]],
  ["Sake", "Japanese ceramic sake cup", ["alcohol", "cheers", "bar"]],
  ["Champagne", "Champagne bottle popping cork", ["celebrate", "party", "toast"]],
  ["Cocktail", "Tropical martini cocktail glass", ["drink", "party", "bar"]],
  ["Tropicaldrink", "Exotic coconut tiki drink", ["beach", "rum", "vacation"]],
  ["Whiskey", "Rock glass bourbon whiskey", ["bar", "drink", "alcohol"]],
  ["Bubbletea", "Sweet boba milk tea", ["boba", "shake", "straw", "tapioca"]],
  ["Juice", "Paper box juice straw", ["kid", "drink", "orange"]],
  ["Mate", "South american mate gourd", ["herbal", "tea", "energy"]],
  ["Ice", "Cold translucent ice cube", ["cold", "water", "freeze"]],
  ["Chopsticks", "Wooden eating chopsticks", ["asia", "sushi", "ramen"]],
  ["Platter", "Steaming dinner plate fork knife", ["restaurant", "lunch", "eat"]],
  ["Spoon", "Silver metallic eating spoon", ["soup", "utensil"]],
  ["Fork", "Silver dining eating fork", ["dinner", "pasta"]]
];

const rawTravelPlaces: RawEmoji[] = [
  ["🚗", "Red passenger car", ["drive", "road-trip", "traffic", "wheels"]],
  ["🚀", "Space travel rocket", ["space", "nasa", "launch", "moon", "galaxy"]],
  ["🛸", "Alien flying UFO saucer", ["space", "cosmic", "sci-fi", "aliens"]],
  ["✈️", "Flying passenger airplane", ["travel", "vacation", "flight", "aeroplane"]],
  ["🚲", "Sports bicycle rider", ["cycle", "fitness", "wheels", "bike"]],
  ["⛲", "Water plaza fountain", ["gardens", "park", "spray", "aesthetic"]],
  ["🗼", "Tokyo tower landmark", ["japan", "eiffel", "travel", "landmark"]],
  ["🗽", "Statue of Liberty New York", ["america", "usa", "monument", "nyc"]],
  ["🏰", "Medieval stone castle", ["disney", "palace", "fairy", "vintage", "fantasy"]],
  ["🏔️", "Snowy peak mountain", ["nature", "climb", "alps", "hiking", "cold"]],
  ["🌋", "Erupting hot volcano", ["lava", "crater", "hawaii", "danger"]],
  ["🏕️", "Wilderness camping tent", ["forest", "outdoor", "nature", "campfire"]],
  ["🏖️", "Sunny beach umbrella", ["summer", "sand", "ocean", "vacation"]],
  ["🏜️", "Arid desert sands", ["warm", "cactus", "sahara", "dry"]],
  ["🌊", "Crashing ocean wave", ["sea", "surf", "tsunami", "water"]],
  ["🌌", "Cosmic milky way galaxy", ["stars", "nebula", "universe", "space"]],
  ["🪐", "Ringed Saturn planet", ["space", "astro", "solar-system", "galaxy"]],
  ["🌙", "Crescent golden moon", ["night", "sky", "sleep", "dreamy", "luna"]],
  ["☀️", "Bright shining sun", ["sunny", "summer", "warm", "weather", "heat"]],
  ["🌧️", "Thundercloud with rain", ["storm", "weather", "sky", "wet"]],
  ["Taxi", "Yellow street cab taxi", ["ride", "uber", "nyc", "drive"]],
  ["SUV", "Blue family SUV car", ["drive", "suburb", "automobile"]],
  ["Bus", "Yellow transit school bus", ["commute", "kids", "education"]],
  ["Trolleybus", "Double wire electric trolleybus", ["commute", "transit", "city"]],
  ["Racecar", "Formula formula 1 racecar", ["fast", "track", "grandprix"]],
  ["Ambulance", "Emergency rescue ambulance sirens", ["hospital", "medical", "siren"]],
  ["Fireengine", "Red firefighter fire engine", ["extinguish", "emergency", "siren"]],
  ["Van", "White transit delivery van", ["cargo", "fedex", "mover"]],
  ["Pickup", "Spacious utility pickup truck", ["farm", "offroad", "utility"]],
  ["Truck", "Large log container truck", ["cargo", "freight", "interstate"]],
  ["Tractor", "Green farming harvest tractor", ["farm", "crop", "agriculture"]],
  ["Scooter", "Two wheels kicks scooter", ["play", "ride", "kid"]],
  ["Wheelchair", "Manual access wheelchair push", ["accessibility", "medical"]],
  ["Motorbike", "Sports street superbike motorcycle", ["fast", "ride", "wheels"]],
  ["Rickshaw", "Auto taxi rickshaw tuktuk", ["asia", "taxi", "commute"]],
  ["Siren", "Flashing revolving red siren", ["police", "alarm", "emergency"]],
  ["Policecar", "High speed police patrol car", ["siren", "cop", "emergency"]],
  ["Station", "Subway metro concrete station", ["transit", "commute", "train"]],
  ["Helicopter", "Whirling rotors sky helicopter", ["flight", "rescue", "chopper"]],
  ["Biplane", "Retro propeller biplane wings", ["vintage", "prop", "flight"]],
  ["Seat", "Passenger cabin window seat", ["airplane", "travel", "ticket"]],
  ["Satellite", "Orbit communications radar satellite", ["space", "signals", "tech"]],
  ["Canoe", "Wooden river lake canoe", ["kayak", "lake", "paddle"]],
  ["Sailboat", "Wind sail catamaran sailboat", ["ocean", "surf", "yacht"]],
  ["Yacht", "Luxury cruises motor yacht", ["rich", "marina", "boat"]],
  ["Cruise", "Grand oceanic cruise liner", ["vacation", "sea", "hotel"]],
  ["Ferry", "Public rivers cars ferry boat", ["commute", "island", "water"]],
  ["Temple", "Greek columns concrete temple", ["monument", "rome", "ruins"]],
  ["Church", "Spire bell brick church", ["christian", "wedding", "prayer"]],
  ["Mosque", "Golden dome minarets mosque", ["muslim", "prayer", "ramadan"]],
  ["Synagogue", "Star of david brick synagogue", ["jewish", "prayer"]],
  ["Shrine", "Red torii gate japanese shrine", ["shinto", "japan", "kyoto"]],
  ["Amusement", "Fair🎡 circus big🎡 top", ["carnival", "fun", "games"]],
  ["Ferrywheel", "Gigantic spinning ferris wheel", ["carnival", "amusement", "date"]],
  ["Rollercoaster", "Loops loops fast rollercoaster curves", ["amusement", "fast", "scream"]],
  ["Map", "Paper folding road map", ["atlas", "navigation", "gps"]],
  ["Compass", "Magnetic needles gold compass direction", ["north", "navigate", "hike"]],
  ["Fuji", "Snow capped sacred Mount Fuji", ["japan", "tokyo", "volcano"]],
  ["Cityscape", "Skyscrapers tall buildings architecture", ["metropolis", "downtown", "skyline"]],
  ["Skyline", "Sunset golden hour city skyline", ["downtown", "warm", "dusk"]],
  ["Bridge", "Suspension red golden gate bridge", ["san-francisco", "roadway"]],
  ["House", "Classic suburban family house", ["home", "address", "family"]],
  ["Building", "Glass concrete corporate office building", ["work", "company", "career"]],
  ["Hospital", "Red cross medical center hospital", ["doctor", "sick", "emergency"]],
  ["Bank", "Golden columns financial bank vaults", ["money", "cash", "mortgage"]],
  ["Hotel", "Bellhop stars luxury resort hotel", ["vacation", "room-service", "stay"]],
  ["School", "Red brick clock tower school", ["education", "kids", "classes"]],
  ["Factory", "Smoking chimneys heavy industrial factory", ["polution", "production", "work"]],
  ["Nebula", "Dust gas stellar nursery nebula", ["cosmos", "stars", "deepspace"]],
  ["Meteor", "Falling streak comet meteor rock", ["space", "armageddon", "wish"]],
  ["Fullmoon", "Luminous bright night full moon", ["luna", "wolf", "halloween"]],
  ["Sunface", "Golden human face shining sun", ["warm", "day", "cheerful"]],
  ["Wind", "Blowing wind swirls drafts gusts", ["breeze", "cool", "winter"]],
  ["Snowflake", "Intricate crystal cold white snowflake", ["winter", "ice", "christmas"]],
  ["Rainbow", "Arched colorful sky prism rainbow", ["magic", "pride", "rain", "potofgold"]],
  ["Umbrella", "Classic open rain weather umbrella", ["wet", "storm", "monsoon"]],
  ["Lightning", "Jagged electric gold bolt lightning", ["storm", "power", " Zeus"]]
];

const rawActivity: RawEmoji[] = [
  ["⚽", "Classic soccer ball", ["sports", "football", "goal", "pitch", "worldcup"]],
  ["🏀", "Orange basketball", ["sports", "hoop", "slam", "nba", "dunk"]],
  ["🏈", "Brown american football", ["sports", "superbowl", "stadium", "quaterback"]],
  ["🎾", "Green tennis ball", ["sports", "racket", "match", "court"]],
  ["🎮", "Gaming gamepad controller", ["play", "gamer", "steam", "playstation", "xbox"]],
  ["🕹️", "Retro arcade joystick", ["play", "classic", "atari", "cabinet", "retro"]],
  ["🎨", "Artists painter palette", ["art", "canvas", "brush", "creative", "drawing"]],
  ["🎭", "Drama performing theater masks", ["acting", "show", "tragedy", "broadway", "drama"]],
  ["🎤", "Vocal singing microphone", ["karaoke", "audio", "voice", "music", "podcast"]],
  ["🎸", "Electric guitar instrument", ["rock", "band", "sound", "music", "amps"]],
  ["🎹", "Musical piano keyboard", ["synth", "keys", "melody", "chords", "concert"]],
  ["🏆", "Golden winner trophy", ["award", "champion", "first", "victory"]],
  ["🎟️", "Admission ticket stub", ["show", "movie", "event", "cinema"]],
  ["🎪", "Circus tent big top", ["clown", "show", "fairground", "acrobat"]],
  ["🎳", "Bowling pins and ball", ["strike", "alley", "game", "pins"]],
  ["Baseball", "White red seams baseball", ["mlb", "bat", "homerun"]],
  ["Softball", "Yellow match softball", ["sports", "game", "pitcher"]],
  ["Volleyball", "White leather match volleyball", ["sports", "beach", "net"]],
  ["Rugby", "Brown oval match rugby ball", ["scrum", "tackle", "six-nations"]],
  ["Yoyo", "Spinning red clutch yoyo", ["toy", "tricks", "string"]],
  ["Pingpong", "Table tennis paddle cell ball", ["sports", "pingpong", "spin"]],
  ["Badminton", "Feathers shuttlecock match badminton racket", ["sports", "net", "court"]],
  ["Hockey", "Ice match hockey puck sticks", ["sports", "nhl", "skate", "canadian"]],
  ["Lacrosse", "Mesh pocket lacrosse stick ball", ["sports", "field", "collegiate"]],
  ["Cricket", "Flat bat leather cricket ball wickets", ["sports", "england", "india", "test"]],
  ["Boomerang", "Curved wooden throwing boomerang", ["australia", "hunt", "wood"]],
  ["Kite", "Diamond flying breeze wind kite", ["toy", "spring", "sky"]],
  ["Archery", "Target dart bow arrows archery", ["precision", "hunt", "bullseye"]],
  ["Fishing", "Lake river reels fishing rod fish", ["hook", "bait", "outdoor"]],
  ["Diving", "Mask snorkel diver flippers diving", ["scuba", "reef", "swim"]],
  ["Boxing", "Red padded punch boxing gloves", ["fight", "knockout", "gym"]],
  ["Martial", "White robe black belt martial arts", ["karate", "judo", "taekwondo"]],
  ["Skateboard", "Street wooden wheels skateboard deck", ["skate", "wheels", "ollie", "grunge"]],
  ["Rollerskate", "Retro quad boots rollerskate wheels", ["derby", "disco", "wheels"]],
  ["Sled", "Wooden snowy mountain sled", ["winter", "slide", "fun"]],
  ["IceSkate", "Silver blade white lace ice skate", ["winter", "figureskating", "hockey"]],
  ["Curling", "Sweeping sliding granite curling stone", ["ice", "winter", "olympics"]],
  ["Ski", "Slalom snowy poles ski boots", ["winter", "resort", "alps"]],
  ["Snowboard", "Fast snow slopes snowboard bindings", ["winter", "shred", "resort"]],
  ["Weight", "Heavy metal barbell weights barbells", ["gym", "workout", "lifting", "muscles"]],
  ["Wrestling", "Double fighters match wrestling ring", ["wwe", "grapple", "combat"]],
  ["Gymnastics", "Bodysuit leotard gymnastics ribbon loops", ["acrobat", "dance", "stretch"]],
  ["Fencing", "Sword protection mask fencing foils", ["epee", "dueling", "fencer"]],
  ["Handball", "Indoor ball match handball goals", ["sports", "olympics"]],
  ["Golf", "Sticks green grass golf ball flag", ["club", "country-club", "putt"]],
  ["HorseRiding", "Jockey saddle race horse galloping", ["equestrian", "derby"]],
  ["Yoga", "Flexible peaceful mat yoga poses", ["meditate", "stretching", "pilates"]],
  ["Surf", "Ocean foam wave surfboard ride", ["beach", "waves", "hawaii"]],
  ["Swimmer", "Water pools splash swimmer goggles", ["swim", "aquatic", "laps"]],
  ["Waterpolo", "Cap splash match waterpolo ball", ["swimming", "goals", "pool"]],
  ["Rowing", "Oars lake crew rowing canoe", ["boat", "regatta", "fitness"]],
  ["Climbing", "Harness chalk mountain climber cliffs", ["hiking", "altitude", "mountaineer"]],
  ["Cycling", "Helmet road bikes cyclist wheels", ["race", "derby", "fitness"]],
  ["Mountainbike", "Dirt shock suspension mountainbike trails", ["offroad", "forest", "trails"]],
  ["Medal", "Golden first place olympic medal", ["award", "champion", "winner"]],
  ["SilverMedal", "Silver second place match medal", ["award", "runnerup"]],
  ["BronzeMedal", "Bronze third place match medal", ["award", "third"]],
  ["Theater", "Venetian gold masks theater show", ["actors", "drama", "plays"]],
  ["Ballet", "Pink silk ballet pointe slippers", ["dance", "dancer", "ballerina"]],
  ["Clapper", "Director scene clapboard slate movie", ["film", "production", "hollywood"]],
  ["Headphone", "Audio studios mixing headphones cups", ["music", "podcast", "dj"]],
  ["Drum", "Percussion snare skins sticks parade drum", ["marchingband", "beats", "rhythm"]],
  ["Brass", "Horn trumpet cylinders brass instruments", ["jazz", "band"]],
  ["Clarinet", "Woodwind tubes keys clarinet instrument", ["orchestra", "jazz"]],
  ["Fiddle", "Strings violin bow cello instruments", ["classical", "orchestra"]],
  ["Slot", "Las vegas casino jackpot slot machine", ["gamble", "coin", "spin"]],
  ["Dice", "Boardgame rolling dots game dice", ["boardgame", "random", "rpg", "yacht"]],
  ["Puzzle", "Jigsaw connected card puzzle piece", ["brain", "smart", "mind"]],
  ["Zodiac", "Double target bullseye darts gameboard", ["aim", "hit", "dart"] ]
];

const rawObjects: RawEmoji[] = [
  ["🧸", "Soft plush teddy bear", ["toy", "cute", "fluffy", "gift", "childhood"]],
  ["🔮", "Mystic crystal ball witch", ["wizard", "magic", "psychic", "fortune", "goth"]],
  ["💿", "Holographic optical CD compact disc", ["music", "album", "retro", "tech", "disk"]],
  ["📷", "Aperture photo camera", ["picture", "lens", "shoot", "hobby", "memories"]],
  ["💻", "Portable laptop software computer", ["tech", "coding", "web", "internet", "developer"]],
  ["📱", "Handheld smartphone cell", ["phone", "screen", "call", "mobile", "text"]],
  ["🔋", "Green battery charge full", ["energy", "power", "tech", "electricity"]],
  ["🕯️", "Wax burning candle flame", ["goth", "cozy", "dark", "witchy", "light"]],
  ["🗝️", "Ancient golden locking key", ["historic", "unlock", "secret", "mystery"]],
  ["📦", "Cardboard package box", ["mail", "shipping", "amazon", "cargo", "delivery"]],
  ["🎁", "Ribbon wrapped gift box", ["present", "holiday", "birthday", "surprise"]],
  ["🎈", "Floating helium red balloon", ["party", "celebration", "clown", "cheerful"]],
  ["🩹", "Sticky band-aid medical plaster", ["heal", "wound", "doctor", "medicine"]],
  ["📚", "Stacked hardcover reading books", ["study", "school", "library", "exam", "novels"]],
  ["💎", "Sparkling blue crystal diamond gem", ["jewelry", "expensive", "luxury", "ring"]],
  ["Crown", "Golden royal jeweled crown", ["king", "queen", "royal", "majesty"]],
  ["Backpack", "School student trail camp backpack", ["books", "hike", "travel"]],
  ["Glasses", "Reading prescription wire glasses", ["vision", "optician", "nerd"]],
  ["Goggles", "Swimming chemical safety lab goggles", ["medical", "protection", "swim"]],
  ["Scarf", "Warm woolen red winter scarf", ["cold", "cozy"]],
  ["Gloves", "Warm gloves knitted winter mittens", ["hands", "cold", "snow"]],
  ["Coat", "Heavy winter padded storm coat", ["jacket", "warm", "rain"]],
  ["Tie", "Business corporate silk neck tie", ["office", "interview", "suit"]],
  ["Shirt", "Casual green collar polo shirt", ["clothes", "wardrobe"]],
  ["Jeans", "Classic blue denim jeans pants", ["indigo", "grunge", "clothes"]],
  ["Dress", "Elegant cocktail party blue dress", ["fashion", "wedding", "glam"]],
  ["Kimono", "Japanese traditional silk floral kimono", ["japan", "kyoto", "clothes"]],
  ["Swimsuit", "Athletic single piece ladies swimsuit", ["swim", "beach", "pool"]],
  ["Briefs", "Mens cotton elastic waistband briefs", ["underwear", "laundry"]],
  ["Shorts", "Mens casual sports cargo shorts", ["summer", "gym"]],
  ["Bikini", "Summertime ladies beach bikini set", ["swim", "sun", "vacation"]],
  ["Purse", "Leather clutch coin metal purse", ["money", "fashion", "shopping"]],
  ["Handbag", "Luxury shoulder leather handbag", ["fashion", "designer", "shopping"]],
  ["Wallet", "Folded brown leather dollar wallet", ["cash", "cards", "wealth"]],
  ["Sneaker", "Running canvas sports tennis sneaker", ["shoes", "gym", "hypebeast"]],
  ["Boot", "Heavy leather winter hiking boot", ["shoes", "climb", "army"]],
  ["Lipstick", "Glossy red cosmetic lipstick tubes", ["makeup", "beauty", "glam"]],
  ["Ring", "Diamond platinum engagement wedding ring", ["love", "propose", "marry"]],
  ["Stethoscope", "Doctor vinyl tubing acoustic stethoscope", ["hospital", "medical", "heart"]],
  ["Pill", "Capsule tablet prescription dose pill", ["pharmacy", "sick", "medical"]],
  ["Syringe", "Medical needle blood flu vaccines", ["hospital", "injection", "covid"]],
  ["Microscope", "Scientific laboratory precision glass microscope", ["science", "biology", "research"]],
  ["Telescope", "Stargazing astronomy galactic lens telescope", ["stars", "planets", "nasa"]],
  ["Firebox", "Red wall emergency fire extinguisher", ["safety", "extinguish", "smoke"]],
  ["Axe", "Felling steel split wood axe", ["firewood", "chopping", "lumberjack"]],
  ["Hammer", "Iron head wood claws hammer", ["tools", "nails", "renovation"]],
  ["Screwdriver", "Flathead phillips orange screw driver", ["tools", "repair", "assembly"]],
  ["Gear", "Rotating mechanical teeth steel gear", ["cogs", "industry", "automation"]],
  ["Scale", "Legal weight balance scales justice", ["court", "attorney", "libra", "law"]],
  ["Chain", "Heavy nested iron links chain", ["metal", "prison", "shackles", "link"]],
  ["Magnet", "Horseshoe red blue poles magnet", ["attract", "forces", "physics"]],
  ["Plug", "Electric wall cords copper plug", ["power", "charging", "tech"]],
  ["Printer", "Laser paper jets desktop printer", ["paperwork", "office", "documents"]],
  ["Keyboard", "Computer keys typing typing keyboard", ["coding", "work", "gaming"]],
  ["Mousepad", "Optical computer lasers clicking mouse", ["tech", "pc", "gamer"]],
  ["Floppy", "Retro black magnetic storage floppy disk", ["retro", "computers", "90s"]],
  ["Film", "Analog reels plastic film strip", ["cinema", "hollywood", "movies"]],
  ["Projector", "Conference rooms ceiling white projector", ["movie", "slide", "work"]],
  ["Television", "CRT dynamic screen retro television set", ["crt", "retro", "vhs", "show"]],
  ["Cassette", "Analog magnetic lofi audio cassette tape", ["retro", "90s", "music", "lofi"]],
  ["Magnifier", "Glass zoom visual reading magnifier lens", ["detective", "search", "zoom"]],
  ["Bulb", "Tungsten glowing glass light bulb", ["idea", "eureka", "smart", "electricity"]],
  ["Flashlight", "Handheld beam battery portable flashlight", ["night", "dark", "camping"]],
  ["Lantern", "Oil burning glass brass lantern", ["camping", "vintage", "cabin"]],
  ["Book", "Closed green hardcover textbook", ["reading", "study", "novels"]],
  ["Scroll", "Ancient rolled papyrus parchment scroll", ["historic", "magic", "wizard", "rpg"]],
  ["Newspaper", "Fresh ink headlines folding newspaper", ["press", "journalism", "news"]],
  ["Tag", "Paper strings pricing labels tagging", ["sale", "store", "brands"]],
  ["Envelope", "White paper letter postage envelope", ["mail", "stamp", "letter"]],
  ["Inbox", "Desk wooden sorting trays inbox", ["mail", "workflow", "office"]],
  ["Folder", "Manila tabs filing papers folder", ["work", "documents", "pc"]],
  ["Calendar", "Spiral grid papers month calendar", ["schedule", "planning", "dates"]],
  ["Pin", "Red plastic bulletin boards thumb pin", ["map", "boards", "office"]],
  ["Paperclip", "Silver wire loops paper clip", ["documents", "office", "attach"]],
  ["Ruler", "Straight markings plastic drawing ruler", ["geometry", "math", "measure"]],
  ["Lock", "Golden shackle lock shut locks", ["security", "password", "private"]],
  ["Key", "Shiny flat metal house key", ["unlock", "home", "car"]],
  ["Broom", "Straw bristle wood sweep broom", ["clean", "halloween", "witch"]],
  ["Basket", "Woven wicker carry harvest basket", ["picnic", "easter", "shopping"]],
  ["Soap", "Scented bath bars white soap bubbles", ["hygiene", "wash", "clean"]],
  ["Razor", "Sharp blade shaving mustache razor", ["hygiene", "barber", "grooming"]],
  ["Shower", "Metallic head dripping spray shower", ["bathroom", "wash", "wet"]],
  ["Bath", "Ceramic clawfoot tub bubbling bath", ["relax", "hygiene", "bathroom"]],
  ["Toilet", "White ceramic dual flush toilet", ["bathroom", "plumbing"]],
  ["Lotion", "Cosmetic squeeze pumps lotion cream", ["skin", "moisture", "beauty"]],
  ["Bell", "Silver counter top desk service bell", ["concierge", "hotel", "ring"]],
  ["Bed", "Wooden pillars cozy mattress bed", ["sleep", "tired", "hotel", "rest"]]
];

const rawSymbols: RawEmoji[] = [
  ["❤️", "Solid red heart", ["love", "valentines", "heart", "romance"]],
  ["💖", "Sparkling pink heart", ["love", "cute", "aesthetic", "shiny"]],
  ["🖤", "Black heart gothic", ["emo", "dark", "heart", "goth"]],
  ["🤍", "Clean white heart", ["hope", "pure", "heart", "minimalist"]],
  ["💔", "Broken cracked heart", ["sad", "pain", "apart", "hurt", "breakup"]],
  ["✨", "Glimmer golden sparkles", ["magic", "shiny", "clean", "star", "aesthetic"]],
  ["⭐", "Bright yellow star", ["shiny", "gold", "astro", "sky", "award"]],
  ["💤", "Sleeping snoring zzz drift", ["sleep", "tired", "bed", "snore"]],
  ["💢", "Anime anger pop popping vein", ["mad", "comic", "rage", "angry"]],
  ["💬", "Speech talk text balloon bubble", ["chat", "speak", "sms", "words"]],
  ["🔄", "Circular sync arrows reload", ["refresh", "cycles", "retry", "loop"]],
  ["♾️", "Infinity endless loop limit", ["math", "forever", "timeless", "always"]],
  ["⚠️", "Yellow warning sign alert", ["danger", "caution", "hazard", "warning"]],
  ["🌀", "Swirl purple cyclone vortex", ["weather", "magic", "spiral", "vortex"]],
  ["🔱", "Golden trident scepter symbol", ["greek", "poseidon", "sea", "trident"]],
  ["🔔", "Gold alert ring bell ringer", ["notify", "sound", "bell", "alarm"]],
  ["🎯", "Bullseye darts precision board", ["aim", "goal", "hit", "darts"]],
  ["OrangeHeart", "Bright orange warmth heart", ["cozy", "fall", "pumpkin"]],
  ["YellowHeart", "Bright yellow sunny heart", ["sun", "friendship", "loyalty"]],
  ["GreenHeart", "Bright natural leaf heart", ["biology", "nature", "eco"]],
  ["BlueHeart", "Bright ocean trust heart", ["peace", "loyalty", "sea"]],
  ["PurpleHeart", "Bright lavender royal heart", ["luxury", "bts", "military"]],
  ["BrownHeart", "Bright cocoa soil heart", ["chocolate", "earth", "fall"]],
  ["RibbonHeart", "Gift wrapped bow knot heart", ["valentine", "presents"]],
  ["Revolving", "Double revolving orbit pink hearts", ["affection", "soulmates"]],
  ["Peace", "Purple round white peace sign", ["hippie", "love", "harmony"]],
  ["Cross", "Purple round white christian cross", ["prayer", "holy"]],
  ["Crescent", "Purple round white islamic crescent", ["ramadan", "muslim"]],
  ["YinYang", "Purple round white balance yinyang", ["harmony", "zen"]],
  ["ZodiacAries", "Purple round white aries ram", ["horoscope", "stars"]],
  ["ZodiacTaurus", "Purple round white taurus bull", ["horoscope", "stars"]],
  ["ZodiacGemini", "Purple round white gemini twins", ["horoscope", "stars"]],
  ["ZodiacCancer", "Purple round white cancer crab", ["horoscope", "stars"]],
  ["ZodiacLeo", "Purple round white leo lion", ["horoscope", "stars"]],
  ["ZodiacVirgo", "Purple round white virgo maiden", ["horoscope", "stars"]],
  ["ZodiacLibra", "Purple round white libra scales", ["horoscope", "scales"]],
  ["ZodiacScorpio", "Purple round white scorpio scorpion", ["horoscope", "stars"]],
  ["ZodiacSagittarius", "Purple round white sagittarius archer", ["horoscope"]],
  ["ZodiacCapricorn", "Purple round white capricorn goat", ["horoscope"]],
  ["ZodiacAquarius", "Purple round white aquarius bearer", ["horoscope"]],
  ["ZodiacPisces", "Purple round white pisces fishes", ["horoscope"]],
  ["Signal", "Orange square icons wireless vibes", ["vibes", "phone", "wifi"]],
  ["Offline", "Orange square icons phones offline", ["silent", "shh"]],
  ["Forbidden", "Red rings slash diagonal stop", ["no", "banned", "rules"]],
  ["Prohibited", "Red lines pedestrian slash walk", ["danger", "stop"]],
  ["NoEntry", "Red round solid white bars", ["stop", "restricted"]],
  ["Hazard", "Red octagonal solid white stop", ["brakes", "warning"]],
  ["NoMobile", "Red diagonal slash smartphone screens", ["digitaldetox", "silent"]],
  ["NoSmoking", "Red diagonal slash burning cigarettes", ["health", "cleanair"]],
  ["Attention", "Heavy outline black exclamation mark", ["alert", "important"]],
  ["Question", "Heavy outline black question mark", ["help", "confused", "faq"]],
  ["HeartExclamation", "Red heavy heart outline mark", ["excitement", "accent"]],
  ["Recycle", "Green twisted triangular arrows cycle", ["nature", "eco", "waste"]],
  ["Accept", "Green green thick check marker", ["pass", "agree", "done"]],
  ["Web", "Blue grids meridian latitude globe", ["internet", "online", "vpn"]],
  ["DiamondBlue", "Large blue square diamond tiles", ["pattern", "aesthetic"]],
  ["DiamondOrange", "Large orange square diamond tiles", ["pattern", "autumn"]],
  ["Zzz", "Snippets snoring grey text lines", ["sleepy", "tired"]],
  ["Bubble", "Three dots chat message bubble", ["typing", "reply", "sms"]],
  ["Notify", "Yellow outline ringing alarm bells", ["sound", "watch", "time"]],
  ["Infinity", "Sleek endless loop loops infinite", ["math", "forever"]],
  ["ArrowUp", "Blue square solid white arrow sky", ["high", "lift"]],
  ["ArrowDown", "Blue square solid white arrow earth", ["low", "drop"]],
  ["ArrowLeft", "Blue square solid white arrow west", ["direction", "back"]],
  ["ArrowRight", "Blue square solid white arrow east", ["direction", "next"]],
  ["Plus", "Grey outline addition basic operators", ["math", "sum"]],
  ["Minus", "Grey outline subtraction basic operators", ["math", "less"]],
  ["Divide", "Grey outline division basic operators", ["math", "shares"]],
  ["Multiply", "Grey outline multiply basic operators", ["math", "times"]],
  ["Dollar", "Green square bold white currency", ["cash", "money", "capitalism"]],
  ["Currency", "Blue square double arrows exchange", ["trade", "forex"]],
  ["Clock12", "Round dials hour minute twelve", ["lunch", "midnight"]],
  ["Clock3", "Round dials hour minute three", ["afternoon", "tea"]],
  ["Clock6", "Round dials hour minute six", ["dinner", "morning"]],
  ["Clock9", "Round dials hour minute nine", ["work", "bedtime"]],
  ["RedCircle", "Large primary color red circle", ["red", "dot"]],
  ["BlueCircle", "Large primary color blue circle", ["blue", "dot"]],
  ["BlackCircle", "Large primary color black circle", ["dark", "dot"]],
  ["WhiteCircle", "Large primary color white circle", ["light", "dot"]],
  ["BlackSquare", "Large primary color black square", ["box", "dark"]],
  ["WhiteSquare", "Large primary color white square", ["box", "light"]],
  ["TriangleUp", "Red outline pointing apex triangle", ["arrow", "play"]],
  ["TriangleDown", "Blue outline pointing base triangle", ["arrow", "drop"]]
];

const rawFlags: RawEmoji[] = [
  ["🏁", "Black-white checkered race flag", ["finish", "formula-1", "grand-prix", "race"]],
  ["🚩", "Triangular red flag alarm alert", ["warning", "toxic", "alert", "danger"]],
  ["🏳️‍🌈", "Rainbow Pride flag beauty", ["lgbtq", "love", "gay", "rights", "pride"]],
  ["🏳️‍⚧️", "Transgender Flag pastel colors", ["lgbtq", "trans", "pride", "gender"]],
  ["🏴‍☠️", "Scary skull pirate black flag", ["pirates", "caribbean", "sea", "treasure"]],
  ["🇺🇸", "United States Flag stars stripes", ["usa", "america", "us", "patriots"]],
  ["🇬🇧", "United Kingdom Union Jack Flag", ["uk", "britain", "england", "london"]],
  ["🇨🇦", "Canada Maple Leaf Flag", ["toronto", "cold", "north", "canadian"]],
  ["🇦🇺", "Australia Flag Southern Cross", ["sydney", "down-under", "outback"]],
  ["🇯🇵", "Japan Rising Sun Flag disk", ["tokyo", "asia", "anime", "japanese"]],
  ["🇩🇪", "Germany Black Red Gold Flag", ["berlin", "europe", "german"]],
  ["🇫🇷", "France Blue White Red Tricolor Flag", ["paris", "europe", "french"]],
  ["🇮🇹", "Italy Green White Red Tricolor Flag", ["rome", "europe", "italian", "pizza"]],
  ["🇪🇸", "Spain Red Yellow Flag coat-arms", ["madrid", "europe", "spanish"]],
  ["🇨🇳", "China Red Flag yellow stars", ["beijing", "asia", "chinese"]],
  ["🇰🇷", "South Korea Flag yin-yang bars", ["seoul", "kpop", "asia"]],
  ["🇮🇳", "India Tricolour Flag ashoka wheel", ["delhi", "asia", "indian"]],
  ["🇧🇷", "Brazil Green Yellow Flag diamond", ["rio", "soccer", "carnival"]],
  ["🇲🇽", "Mexico Flag eagle cactus tricolor", ["cancun", "latin-america", "mexican"]],
  ["🇷🇺", "Russia White Blue Red Flag", ["moscow", "siberia"]],
  ["🇿🇦", "South Africa Rainbow Flag curves", ["cape-town", "safari"]],
  ["🇳🇬", "Nigeria Green White Green stripes", ["lagos", "africa"]],
  ["🇪🇬", "Egypt Tricolor Flag golden eagle", ["cairo", "pyramids", "nile"]],
  ["🇸🇦", "Saudi Arabia Green Flag sword inscription", ["mecca", "desert"]],
  ["🇹🇷", "Turkey Red Flag white crescent star", ["istanbul", "bazaar"]],
  ["🇮🇩", "Indonesia Red Over White Flag", ["bali", "jakarta"]],
  ["🇵🇭", "Philippines Flag sun triangles blue red", ["manila", "islands"]],
  ["🇸🇬", "Singapore Flag crescent five stars red", ["merlion", "asia"]],
  ["🇲🇾", "Malaysia Flag stripes crescent star yellow", ["kuala-lumpur"]],
  ["🇹🇭", "Thailand Flag blue red white stripes", ["bangkok", "phuket"]],
  ["🇳🇿", "New Zealand Flag southern cross union", ["kiwi", "auckland"]],
  ["🇮🇪", "Ireland Green White Orange Flag", ["dublin", "lucky", "clover"]],
  ["🇳🇱", "Netherlands Red White Blue stripes", ["amsterdam", "tulip", "dike"]],
  ["🇧🇪", "Belgium Black Yellow Red stripes", ["brussels", "waffle", "chocolate"]],
  ["🇨🇭", "Switzerland Red Square white cross", ["alps", "geneva", "watch"]],
  ["🇸🇪", "Sweden Blue Flag yellow cross", ["stockholm", "nordic", "ikea"]],
  ["🇳🇴", "Norway Red Flag blue white cross", ["oslo", "nordic", "fjords"]],
  ["🇫🇮", "Finland White Flag blue cross", ["helsinki", "nordic", "cold"]],
  ["🇩🇰", "Denmark Red Flag white cross", ["copenhagen", "nordic"]],
  ["🇵🇱", "Poland White Over Red Flag", ["warsaw", "europe"]],
  ["🇺🇦", "Ukraine Blue Over Yellow Flag", ["kyiv", "sunflower"]],
  ["🇬🇷", "Greece Blue White Cross stripes Flag", ["athens", "islands", "gyros"]],
  ["🇵🇹", "Portugal Green Red Flag armillary", ["lisbon", "coast"]],
  ["🇦🇹", "Austria Red White Red stripes Flag", ["vienna", "alps"]],
  ["🇨🇿", "Czech Republic Flag blue wedges tricolor", ["prague"]],
  ["🇭🇺", "Hungary Red White Green stripes Flag", ["budapest"]],
  ["🇷🇴", "Romania Blue Yellow Red stripes Flag", ["bucharest"]],
  ["🇧🇬", "Bulgaria White Green Red stripes Flag", ["sofia"]],
  ["🇨🇱", "Chile Flag star blue red white", ["santiago", "andes"]],
  ["🇨🇴", "Colombia Yellow Blue Red stripes Flag", ["bogota", "coffee"]],
  ["🇵🇪", "Peru Red White Red stripes Flag", ["lima"]],
  ["🇦🇷", "Argentina Blue White flag golden sun", ["buenosaires", "messi"]],
  ["🇻🇪", "Venezuela Flag yellow blue red stars", ["caracas"]],
  ["🇪🇨", "Ecuador Flag tricolor coat of arms", ["quito", "galapagos"]],
  ["🇺🇾", "Uruguay Flag sun of may stripes", ["montevideo"]],
  ["🇵🇾", "Paraguay Flag horizontal tricolor seal", ["asuncion"]],
  ["🇧🇴", "Bolivia Flag red yellow green coat", ["lapaz"]],
  ["🇵🇷", "Puerto Rico Flag blue triangle white star", ["sanjuan"]],
  ["🇨🇺", "Cuba Flag red triangle white star stripes", ["havana"]],
  ["🇯🇲", "Jamaica Flag green black gold cross", ["kingston", "reggae"]],
  ["🇨🇷", "Costa Rica Flag blue white red stripes", ["puravida"]],
  ["🇵🇦", "Panama Flag quadrants star blue red", ["canal"]],
  ["🇸🇻", "El Salvador Flag blue white blue coat", ["sansalvador"]],
  ["🇬🇹", "Guatemala Flag vertical stripes quetzal", ["antigua"]],
  ["🇭🇳", "Honduras Flag blue white blue stars", ["tegucigalpa"]],
  ["🇳🇮", "Nicaragua Flag blue white blue gold triangle", ["managua"]],
  ["🇹🇹", "Trinidad and Tobago Flag diagonal black red", ["portofspain"]],
  ["🇮🇱", "Israel Blue Star of David flag", ["jerusalem", "telaviv"]],
  ["🇵🇰", "Pakistan Green Flag crescent white star", ["islamabad"]],
  ["🇧🇩", "Bangladesh Green Flag red circle", ["dhaka"]],
  ["🇱🇰", "Sri Lanka Lion Flag green orange crimson", ["colombo"]],
  ["🇳🇵", "Nepal Flag double pennant triangular", ["everest", "kathmandu"]],
  ["🇰🇿", "Kazakhstan Blue Flag golden sun eagle", ["astana", "steppe"]],
  ["🚩", "Triangular Red Flag alerts", ["caution"]],
  ["🏳️", "Pure white flag surrender", ["peace", "stop"]],
  ["🏴", "Pure black flag anarchy", ["rebel", "goth"]],
  ["🏁", "Checkered flags racing lines", ["race", "fast", "car"]]
];

// Helper to expand specific word keys to actual standard single-character emojis
// This avoids code compiling errors with symbols like `Ant` or standard keywords
const emojiAliasMap: Record<string, string> = {
  "BONE": "🦴", "Ant": "🐜", "Mosquito": "🦟", "Shark": "🦈", "Leopard": "🐆",
  "Tiger": "🐅", "Cow": "🐄", "Deer": "🦌", "Camel": "🐪", "Elephant": "🐘",
  "Rhinoceros": "🦏", "Mouse": "🐭", "Rabbit": "🐇", "Chipmunk": "🐿️",
  "Trees": "🌳", "Cactus": "🌵", "Herb": "🌿", "Maple": "🍁", "Mushroom": "🍄",
  "Shell": "🐚", "Rock": "🪨", "Wood": "🪵", "Sunflower": "🌻", "Tulip": "🌷",
  "Christmas": "🎄", "Onion": "🧅", "Garlic": "🧄", "Pear": "🍐", "Orange": "🍊",
  "Lemon": "🍋", "Banana": "🍌", "Grapes": "🍇", "Blueberry": "🫐", "Melon": "🍈",
  "Peach": "🍑", "Mango": "🥭", "Pineapple": "🍍", "Coconut": "🥥", "Kiwi": "🥝",
  "Tomato": "🍅", "Aubergine": "🍆", "Broccoli": "🥦", "Lettuce": "🥬",
  "Cucumber": "🥒", "Chili": "🌶️", "Corn": "🌽", "Carrot": "🥕", "Potato": "🥔",
  "Bread": "🍞", "Croissant": "🥐", "Baguette": "🥖", "Flatbread": "🫓",
  "Pretzel": "🥨", "Bagel": "🥯", "Pancakes": "🥞", "Waffle": "🧇", "Cheese": "🧀",
  "Meat": "🥩", "Poultry": "🍗", "Bacon": "🥓", "Hotdog": "🌭", "Sandwich": "🥪",
  "Burrito": "🌯", "Popcorn": "🍿", "Bento": "🍱", "Ricecracker": "🍘",
  "Riceball": "🍙", "Rice": "🍚", "Yam": "🍠", "Oden": "🍢", "Fishcake": "🍥",
  "Mooncake": "🥮", "Dango": "🍡", "Dumpling": "🥟", "Oyster": "🦪",
  "Shavedice": "🍧", "Sundae": "🍨", "Cake": "🎂", "Chocolate": "🍫",
  "Candy": "🍬", "Lollipop": "🍭", "Custard": "🍮", "Honey": "🍯",
  "Babybottle": "🍼", "Milk": "🥛", "Teapot": "🫖", "Sake": "🍶",
  "Champagne": "🍾", "Cocktail": "🍸", "Tropicaldrink": "🍹", "Whiskey": "🥃",
  "Bubbletea": "🧋", "Juice": "🧃", "Mate": "🧉", "Ice": "🧊", "Chopsticks": "🥢",
  "Platter": "🍽️", "Spoon": "🥄", "Fork": "🍴", "Taxi": "🚕", "SUV": "🚙",
  "Bus": "🚌", "Trolleybus": "🚎", "Racecar": "🏎️", "Ambulance": "🚑",
  "Fireengine": "🚒", "Van": "🚐", "Pickup": "🛻", "Truck": "🚚", "Tractor": "🚜",
  "Scooter": "🛴", "Wheelchair": "🦽", "Motorbike": "🏍️", "Rickshaw": "🛺",
  "Siren": "🚨", "Policecar": "🚓", "Station": "🚉", "Helicopter": "🚁",
  "Biplane": "🛩️", "Seat": "💺", "Satellite": "🛰️", "Canoe": "🛶",
  "Sailboat": "⛵", "Yacht": "🛥️", "Cruise": "🛳️", "Ferry": "⛴️",
  "Temple": "🏛️", "Church": "⛪", "Mosque": "🕌", "Synagogue": "🕍",
  "Shrine": "⛩️", "Amusement": "🎪", "Ferrywheel": "🎡", "Rollercoaster": "🎢",
  "Map": "🗺️", "Compass": "🧭", "Fuji": "🗻", "Cityscape": "🏙️",
  "Skyline": "🌇", "Bridge": "🌉", "House": "🏠", "Building": "🏢",
  "Hospital": "🏥", "Bank": "🏦", "Hotel": "🏨", "School": "🏫",
  "Factory": "🏭", "Nebula": "🌌", "Meteor": "🌠", "Fullmoon": "🌕",
  "Sunface": "🌞", "Wind": "💨", "Snowflake": "❄️", "Rainbow": "🌈",
  "Umbrella": "☔", "Lightning": "⚡", "Baseball": "⚾", "Softball": "🥎",
  "Volleyball": "🏐", "Rugby": "🏉", "Yoyo": "🪀", "Pingpong": "🏓",
  "Badminton": "🏸", "Hockey": "🏑", "Lacrosse": "🥍", "Cricket": "🏏",
  "Boomerang": "🪃", "Kite": "🪁", "Archery": "🏹", "Fishing": "🎣",
  "Diving": "🤿", "Boxing": "🥊", "Martial": "🥋", "Skateboard": "🛹",
  "Rollerskate": "🛼", "Sled": "🛷", "IceSkate": "⛸️", "Curling": "🥌",
  "Ski": "🎿", "Snowboard": "🏂", "Weight": "🏋️", "Wrestling": "🤼",
  "Gymnastics": "🤸", "Fencing": "🤺", "Handball": "🤾", "Golf": "⛳",
  "HorseRiding": "🏇", "Yoga": "🧘", "Surf": "🏄", "Swimmer": "🏊",
  "Waterpolo": "🤽", "Rowing": "🚣", "Climbing": "🧗", "Cycling": "🚴",
  "Mountainbike": "🚵", "Medal": "🥇", "SilverMedal": "🥈", "BronzeMedal": "🥉",
  "Theater": "🎭", "Ballet": "🩰", "Clapper": "🎬", "Headphone": "🎧",
  "Drum": "🥁", "Brass": "🎺", "Clarinet": "🎷", "Fiddle": "🎻", "Slot": "🎰",
  "Dice": "🎲", "Puzzle": "🧩", "Zodiac": "🎯", "Crown": "👑", "Backpack": "🎒",
  "Glasses": "👓", "Goggles": "🥽", "Scarf": "🧣", "Gloves": "🧤",
  "Coat": "🧥", "Tie": "👔", "Shirt": "👕", "Jeans": "👖", "Dress": "👗",
  "Kimono": "👘", "Swimsuit": "🩱", "Briefs": "🩲", "Shorts": "🩳",
  "Bikini": "👙", "Purse": "👛", "Handbag": "👜", "Wallet": "👝",
  "Sneaker": "👟", "Boot": "🥾", "Lipstick": "💄", "Ring": "💍",
  "Stethoscope": "🩺", "Pill": "💊", "Syringe": "💉", "Microscope": "🔬",
  "Telescope": "🔭", "Firebox": "🧯", "Axe": "🪓", "Hammer": "🔨",
  "Screwdriver": "🪛", "Gear": "⚙️", "Scale": "⚖️", "Chain": "⛓️",
  "Magnet": "🧲", "Plug": "🔌", "Printer": "🖨️", "Keyboard": "⌨",
  "Mousepad": "🖱️", "Floppy": "💾", "Film": "🎞️", "Projector": "📽️",
  "Television": "📺", "Cassette": "📼", "Magnifier": "🔍", "Bulb": "💡",
  "Flashlight": "🔦", "Lantern": "🏮", "Book": "📖", "Scroll": "📜",
  "Newspaper": "📰", "Tag": "🏷️", "Envelope": "✉️", "Inbox": "📥",
  "Folder": "📁", "Calendar": "📅", "Pin": "📌", "Paperclip": "📎",
  "Ruler": "📏", "Lock": "🔒", "Key": "🔑", "Broom": "🧹", "Basket": "🧺",
  "Soap": "🧼", "Razor": "🪒", "Shower": "🚿", "Bath": "🛁", "Toilet": "🚽",
  "Lotion": "🧴", "Bell": "🔔", "Bed": "🛌", "OrangeHeart": "🧡",
  "YellowHeart": "💛", "GreenHeart": "💚", "BlueHeart": "💙", "PurpleHeart": "💜",
  "BrownHeart": "🤎", "RibbonHeart": "💝", "Revolving": "💞", "Peace": "☮️",
  "Cross": "✝️", "Crescent": "☪️", "YinYang": "☯️", "ZodiacAries": "♈",
  "ZodiacTaurus": "♉", "ZodiacGemini": "♊", "ZodiacCancer": "♋", "ZodiacLeo": "♌",
  "ZodiacVirgo": "♍", "ZodiacLibra": "♎", "ZodiacScorpio": "♏", "ZodiacSagittarius": "♐",
  "ZodiacCapricorn": "♑", "ZodiacAquarius": "♒", "ZodiacPisces": "♓", "Signal": "📶",
  "Offline": "📴", "Forbidden": "🚫", "Prohibited": "🚷", "NoEntry": "⛔",
  "Hazard": "⚠️", "NoMobile": "📵", "NoSmoking": "🚭", "Attention": "❗",
  "Question": "❓", "HeartExclamation": "❣️", "Recycle": "♻️", "Accept": "✅",
  "Web": "🌐", "DiamondBlue": "🔷", "DiamondOrange": "🔸", "Zzz": "💤",
  "Bubble": "💬", "Notify": "🔔", "Infinity": "♾️", "ArrowUp": "⬆️",
  "ArrowDown": "⬇️", "ArrowLeft": "⬅️", "ArrowRight": "➡️", "Plus": "➕",
  "Minus": "➖", "Divide": "➗", "Multiply": "✖️", "Dollar": "💲",
  "Currency": "💱", "Clock12": "🕛", "Clock3": "🕒", "Clock6": "🕕",
  "Clock9": "🕘", "RedCircle": "🔴", "BlueCircle": "🔵", "BlackCircle": "⚫",
  "WhiteCircle": "⚪", "BlackSquare": "⬛", "WhiteSquare": "⬜", "TriangleUp": "▲",
  "TriangleDown": "▼"
};

const mapRaw = (raw: RawEmoji[]): EmojiItem[] => {
  return raw.map(([keyOrEmoji, name, keywords]) => {
    // Check if key is in alias map
    const mappedEmoji = emojiAliasMap[keyOrEmoji] || keyOrEmoji;
    return {
      emoji: mappedEmoji,
      name,
      keywords
    };
  });
};

export const CuratedEmojis: Record<string, EmojiItem[]> = {
  smileys_people: mapRaw(rawSmileysPeople),
  animals_nature: mapRaw(rawAnimalsNature),
  food_drink: mapRaw(rawFoodDrink),
  travel_places: mapRaw(rawTravelPlaces),
  activity: mapRaw(rawActivity),
  objects: mapRaw(rawObjects),
  symbols: mapRaw(rawSymbols),
  flags: mapRaw(rawFlags)
};
